import { useEffect, useState, type ReactNode } from 'react';
import { Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { MerchantBusinessType, MerchantProfileForm, MerchantProfileUpdateRequest, MerchantSelfProfileDto } from '@/contracts/merchantProfile';
import { merchantBusinessTypes } from '@/contracts/merchantProfile';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { merchantProfileToForm, merchantProfileUpdatePayload } from '@/features/merchantProfile/presentation';
import { merchantProfileFormSchema } from '@/features/merchantProfile/validation';
import { InlineError, MutationLoading, StatusBadge } from '@/components/native/ScreenStates';

export function MerchantProfileView({ profile, saving, apiError, success, onSave }: { profile: MerchantSelfProfileDto; saving: boolean; apiError?: string; success?: ReactNode; onSave: (input: MerchantProfileUpdateRequest) => void }) {
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState(() => merchantProfileToForm(profile));
  const [validationError, setValidationError] = useState('');
  useEffect(() => { if (!editing) setForm(merchantProfileToForm(profile)); }, [editing, profile]);
  useEffect(() => { setEditing(false); setForm(merchantProfileToForm(profile)); }, [profile.timestamps.updatedAt]);
  const change = (key: keyof MerchantProfileForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const save = () => { const parsed = merchantProfileFormSchema.safeParse(form); if (!parsed.success) { setValidationError(parsed.error.issues[0]?.message ?? 'Check the form and try again.'); return; } setValidationError(''); onSave(merchantProfileUpdatePayload(parsed.data)); };
  const cancel = () => { setForm(merchantProfileToForm(profile)); setValidationError(''); setEditing(false); };

  return <View style={styles.root}>
    <View style={styles.summary}>
      {profile.profilePhotoUrl ? <Image accessibilityLabel={`${profile.fullName} profile photo`} source={{ uri: profile.profilePhotoUrl }} style={styles.avatar} /> : <View style={styles.avatarFallback}><Text style={styles.initial}>{profile.fullName.slice(0, 1).toUpperCase() || 'M'}</Text></View>}
      <View style={styles.summaryText}><Text style={styles.name}>{profile.fullName}</Text><Text style={styles.business}>{profile.business.name}</Text><Text style={styles.phone}>{profile.phone}</Text><View style={styles.badges}><StatusBadge label={profile.access.status} tone={profile.access.status === 'ACTIVE' ? 'success' : 'error'} /><StatusBadge label={profile.onboarding.completed ? 'Onboarding complete' : 'Onboarding pending'} tone={profile.onboarding.completed ? 'success' : 'warning'} /></View></View>
    </View>
    {success}
    {editing ? <View style={styles.form}>
      <Section title="Personal"><Input label="Full name" value={form.fullName} onChange={(v) => change('fullName', v)} /><Input label="Email" keyboardType="email-address" autoCapitalize="none" value={form.email} onChange={(v) => change('email', v)} /><Input label="Profile photo HTTPS URL" autoCapitalize="none" value={form.profilePhotoUrl} onChange={(v) => change('profilePhotoUrl', v)} /></Section>
      <Section title="Business"><Input label="Business name" value={form.businessName} onChange={(v) => change('businessName', v)} /><Text style={styles.label}>Business type</Text><View style={styles.options}>{merchantBusinessTypes.map((type) => <Pressable key={type} onPress={() => change('businessType', type)} style={[styles.option, form.businessType === type && styles.optionSelected]}><Text style={[styles.optionText, form.businessType === type && styles.optionTextSelected]}>{type}</Text></Pressable>)}</View><Input label="GST number" autoCapitalize="characters" value={form.gstNumber} onChange={(v) => change('gstNumber', v)} /><Input label="PAN number" autoCapitalize="characters" value={form.panNumber} onChange={(v) => change('panNumber', v)} /></Section>
      <Section title="Business address"><Input multiline label="Address" value={form.businessAddress} onChange={(v) => change('businessAddress', v)} /><Input label="City" value={form.city} onChange={(v) => change('city', v)} /><Input label="State" value={form.state} onChange={(v) => change('state', v)} /><Input label="Pincode" keyboardType="number-pad" value={form.pincode} onChange={(v) => change('pincode', v)} /></Section>
      <Section title="Payment"><Input label="Payment QR HTTPS URL" autoCapitalize="none" value={form.paymentQrUrl} onChange={(v) => change('paymentQrUrl', v)} /><Input label="UPI ID" autoCapitalize="none" value={form.upiId} onChange={(v) => change('upiId', v)} /></Section>
      {validationError ? <InlineError message={validationError} /> : null}{apiError ? <InlineError message={apiError} /> : null}{saving ? <MutationLoading label="Saving profile…" /> : null}
      <View style={styles.actions}><Button label="Cancel" secondary disabled={saving} onPress={cancel} /><Button label={saving ? 'Saving…' : 'Save profile'} disabled={saving} onPress={save} /></View>
    </View> : <View style={styles.form}>
      <Section title="Contact"><Field label="Phone" value={profile.phone} /><Field label="Email" value={profile.email} /><Field label="Profile photo" value={profile.profilePhotoUrl} /></Section>
      <Section title="Business"><Field label="Business name" value={profile.business.name} /><Field label="Business type" value={profile.business.type} /><Field label="GST number" value={profile.business.gstNumber} /><Field label="PAN number" value={profile.business.panNumber} /></Section>
      <Section title="Business address"><Field label="Address" value={profile.address.businessAddress} /><Field label="City" value={profile.address.city} /><Field label="State" value={profile.address.state} /><Field label="Pincode" value={profile.address.pincode} /></Section>
      <Section title="Payment"><Field label="Payment QR URL" value={profile.payment.qrUrl} /><Field label="UPI ID" value={profile.payment.upiId} /></Section>
      <Button label="Edit profile" onPress={() => setEditing(true)} />
    </View>}
  </View>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Field({ label, value }: { label: string; value: string | null }) { return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><Text selectable style={[styles.fieldValue, !value && styles.empty]}>{value || 'Not provided'}</Text></View>; }
function Input({ label, value, onChange, multiline, autoCapitalize = 'words', keyboardType = 'default' }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; autoCapitalize?: 'none' | 'words' | 'characters'; keyboardType?: 'default' | 'email-address' | 'number-pad' }) { return <View style={styles.control}><Text style={styles.label}>{label}</Text><TextInput autoCapitalize={autoCapitalize} keyboardType={keyboardType} multiline={multiline} onChangeText={onChange} placeholderTextColor={colors.textTertiary} style={[styles.input, multiline && styles.multiline]} value={value} /></View>; }
function Button({ label, onPress, secondary, disabled }: { label: string; onPress: () => void; secondary?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.secondary, (pressed || disabled) && styles.pressed]}><Text style={[styles.buttonText, secondary && styles.secondaryText]}>{label}</Text></Pressable>; }

const styles = StyleSheet.create({
  root: { gap: spacing.lg }, form: { gap: spacing.lg }, summary: { flexDirection: 'row', gap: spacing.lg, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, avatar: { width: 76, height: 76, borderRadius: radius.full, backgroundColor: colors.surfaceMuted }, avatarFallback: { width: 76, height: 76, alignItems: 'center', justifyContent: 'center', borderRadius: radius.full, backgroundColor: colors.primaryMuted }, initial: { color: colors.primaryDark, fontFamily: fontFamilies.headingBold, fontSize: 30 }, summaryText: { flex: 1, gap: spacing.xs }, name: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 20 }, business: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 14 }, phone: { color: colors.textSecondary, fontFamily: fontFamilies.numbersRegular, fontSize: 13 }, badges: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.xs }, section: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, sectionTitle: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 18 }, field: { gap: spacing.xxs, paddingBottom: spacing.sm, borderBottomColor: colors.divider, borderBottomWidth: 1 }, fieldLabel: { color: colors.textTertiary, fontFamily: fontFamilies.bodyMedium, fontSize: 12 }, fieldValue: { color: colors.textPrimary, fontFamily: fontFamilies.body, fontSize: 15, lineHeight: 21 }, empty: { color: colors.textTertiary, fontStyle: 'italic' }, control: { gap: spacing.xs }, label: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 13 }, input: { minHeight: touchTarget.min, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, color: colors.textPrimary, backgroundColor: colors.background, borderColor: colors.borderStrong, borderRadius: radius.control, borderWidth: 1, fontFamily: fontFamilies.body, fontSize: 15 }, multiline: { minHeight: 88, textAlignVertical: 'top' }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, option: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.surfaceMuted, borderRadius: radius.chip }, optionSelected: { backgroundColor: colors.primaryDark }, optionText: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 12 }, optionTextSelected: { color: colors.textOnPrimary }, actions: { flexDirection: 'row', gap: spacing.sm }, button: { flex: 1, minHeight: touchTarget.min, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.primaryDark, borderRadius: radius.control }, secondary: { backgroundColor: colors.surfaceMuted }, buttonText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 14 }, secondaryText: { color: colors.textPrimary }, pressed: { opacity: 0.6 },
});
