import { useState, type ReactNode } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { StyleSheet, Text, View } from 'react-native';
import type { VisitRescheduleInput } from '@/contracts/merchantVisit';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { ConfirmationAction, InlineError, LoadingState, MutationLoading, RetryState, StatusBadge, SuccessFeedback } from '@/components/native/ScreenStates';
import { RescheduleVisitModal, VisitActions, visitActionLabel } from '@/components/native/visits/VisitActions';
import { colors, fontFamilies, radius, spacing } from '@/design-system';
import { useCompleteVisit, useConfirmVisit, useMarkVisitNoShow, useMerchantVisit, useRejectVisit, useRescheduleVisit } from '@/features/merchantVisits/hooks/useMerchantVisits';
import { displayVisitStatus } from '@/features/merchantVisits/mapper';
import { merchantVisitError, visitStatusTone } from '@/features/merchantVisits/presentation';
import type { MerchantVisitAction } from '@/features/merchantVisits/transitions';

export default function VisitDetail() {
  const params = useLocalSearchParams<{ id?: string }>(); const id = typeof params.id === 'string' ? params.id : ''; const query = useMerchantVisit(id); const confirm = useConfirmVisit(); const reject = useRejectVisit(); const complete = useCompleteVisit(); const noShow = useMarkVisitNoShow(); const reschedule = useRescheduleVisit();
  const [pending, setPending] = useState<Exclude<MerchantVisitAction, 'reschedule'> | null>(null); const [showReschedule, setShowReschedule] = useState(false); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const busy = confirm.isPending || reject.isPending || complete.isPending || noShow.isPending || reschedule.isPending;
  const done = (message: string) => { setError(''); setNotice(message); setPending(null); }; const fail = (reason: unknown) => { setNotice(''); setError(merchantVisitError(reason)); setPending(null); };
  const perform = () => { if (!pending) return; const options = { onSuccess: () => done(`Visit ${visitActionLabel(pending).toLowerCase()} successful.`), onError: fail }; if (pending === 'confirm') confirm.mutate({ id }, options); else if (pending === 'reject') reject.mutate({ id }, options); else if (pending === 'complete') complete.mutate({ id }, options); else noShow.mutate({ id }, options); };
  const submitReschedule = (input: VisitRescheduleInput) => reschedule.mutate({ id, ...input }, { onSuccess: () => { setShowReschedule(false); done('Visit reschedule requested.'); }, onError: fail });
  const action = (next: MerchantVisitAction) => { setNotice(''); setError(''); if (next === 'reschedule') setShowReschedule(true); else setPending(next); };
  return <MerchantScreen title="Visit Detail" showBack refreshing={query.isRefetching} onRefresh={() => void query.refetch()}>{query.isPending ? <LoadingState label="Loading visit details..." /> : query.isError || !query.data ? <RetryState title="Could not load visit" message={merchantVisitError(query.error)} onRetry={() => void query.refetch()} /> : <View style={styles.content}><View style={styles.heading}><View style={styles.grow}><Text style={styles.name}>{query.data.user.name}</Text><Text style={styles.pg}>{query.data.pg.name}</Text></View><StatusBadge label={displayVisitStatus(query.data.status)} tone={visitStatusTone(query.data.status)} /></View><Section title="Visitor"><Field label="Phone" value={query.data.user.phone} /><Field label="Email" value={query.data.user.email ?? 'Not provided'} /></Section><Section title="Property"><Field label="PG" value={query.data.pg.name} /><Field label="Address" value={[query.data.pg.location.address, query.data.pg.location.locality, query.data.pg.location.city].filter(Boolean).join(', ')} /></Section><Section title="Schedule"><Field label="Date" value={query.data.requestedDate} /><Field label="Time" value={query.data.requestedTime} /><Field label="Created" value={new Date(query.data.createdAt).toLocaleString('en-IN')} /><Field label="Updated" value={new Date(query.data.updatedAt).toLocaleString('en-IN')} /></Section><Section title="Note"><Text style={styles.value}>{query.data.note ?? 'No note provided.'}</Text></Section><VisitActions status={query.data.status} busy={busy} onAction={action} />{notice ? <SuccessFeedback message={notice} /> : null}{error ? <InlineError message={error} /> : null}{busy ? <MutationLoading label="Updating visit..." /> : null}</View>}<ConfirmationAction visible={Boolean(pending)} title={`${pending ? visitActionLabel(pending) : 'Update'} visit?`} message="The backend will validate the current visit state before applying this action." confirmLabel={pending ? visitActionLabel(pending) : 'Update'} busy={busy} onCancel={() => setPending(null)} onConfirm={perform} /><RescheduleVisitModal visible={showReschedule} busy={reschedule.isPending} onClose={() => setShowReschedule(false)} onSubmit={submitReschedule} /></MerchantScreen>;
}
function Section({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Field({ label, value }: { label: string; value: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: spacing.lg }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, grow: { flex: 1 }, name: { color: colors.textPrimary, fontFamily: fontFamilies.headingBold, fontSize: 25 }, pg: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 14 }, section: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, sectionTitle: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 17 }, field: { gap: spacing.xxs }, label: { color: colors.textTertiary, fontFamily: fontFamilies.bodyMedium, fontSize: 11 }, value: { color: colors.textPrimary, fontFamily: fontFamilies.body, fontSize: 14, lineHeight: 21 } });
