import { useState, type ReactNode } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import type { MerchantOnboardingCompleteRequest, MerchantOnboardingForm } from '@/contracts/merchantOnboarding';
import { merchantBusinessTypes, type MerchantSelfProfileDto } from '@/contracts/merchantProfile';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { onboardingFormFromProfile, onboardingPayload } from '@/features/merchantOnboarding/presentation';
import { merchantOnboardingSchema } from '@/features/merchantOnboarding/validation';
import { InlineError } from '@/components/native/ScreenStates';

const titles = ['About you', 'Your PG business', 'Payment details'] as const;
export function MerchantOnboardingFormView({ profile, pending, apiError, onSubmit }: { profile: MerchantSelfProfileDto; pending: boolean; apiError?: string; onSubmit: (input: MerchantOnboardingCompleteRequest) => void }) {
  const [step, setStep] = useState(0); const [form, setForm] = useState(() => onboardingFormFromProfile(profile)); const [error, setError] = useState('');
  const change = (field: keyof MerchantOnboardingForm, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const next = () => { const fields = step === 0 ? ['fullName', 'businessName', 'businessType'] as const : ['city'] as const; const result = merchantOnboardingSchema.pick(Object.fromEntries(fields.map((field) => [field, true])) as never).safeParse(form); if (!result.success) { setError(result.error.issues[0]?.message ?? 'Check the fields and try again.'); return; } setError(''); setStep((current) => Math.min(2, current + 1)); };
  const submit = () => { if (pending) return; const result = merchantOnboardingSchema.safeParse(form); if (!result.success) { setError(result.error.issues[0]?.message ?? 'Check the form and try again.'); return; } setError(''); onSubmit(onboardingPayload(result.data)); };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <Text style={styles.brand}>STAYNEST · MERCHANT</Text><Text style={styles.heading}>Complete your profile</Text><Text style={styles.subtitle}>Step {step + 1} of 3 · {titles[step]}</Text><View style={styles.progress}><View style={[styles.progressFill, { width: `${((step + 1) / 3) * 100}%` }]} /></View>
    {step === 0 ? <Card title="About you"><Input label="Full name *" value={form.fullName} onChange={(v) => change('fullName', v)} /><ReadOnly label="Verified phone" value={profile.phone} /><Input label="Email (optional)" autoCapitalize="none" keyboardType="email-address" value={form.email} onChange={(v) => change('email', v)} /><Input label="Profile photo HTTPS URL (optional)" autoCapitalize="none" value={form.profilePhotoUrl} onChange={(v) => change('profilePhotoUrl', v)} /><Input label="PG / business name *" value={form.businessName} onChange={(v) => change('businessName', v)} /><Text style={styles.label}>Business type *</Text><View style={styles.options}>{merchantBusinessTypes.map((type) => <Pressable key={type} onPress={() => change('businessType', type)} style={[styles.option, form.businessType === type && styles.optionSelected]}><Text style={[styles.optionText, form.businessType === type && styles.optionTextSelected]}>{type}</Text></Pressable>)}</View></Card> : null}
    {step === 1 ? <Card title="Your PG business"><Input multiline label="Business address (optional)" value={form.businessAddress} onChange={(v) => change('businessAddress', v)} /><Input label="City *" value={form.city} onChange={(v) => change('city', v)} /><Input label="State (optional)" value={form.state} onChange={(v) => change('state', v)} /><Input label="Pincode (optional)" keyboardType="number-pad" value={form.pincode} onChange={(v) => change('pincode', v)} /><Input label="GST number (optional)" autoCapitalize="characters" value={form.gstNumber} onChange={(v) => change('gstNumber', v)} /><Input label="PAN number (optional)" autoCapitalize="characters" value={form.panNumber} onChange={(v) => change('panNumber', v)} /></Card> : null}
    {step === 2 ? <Card title="Payment details"><Text style={styles.help}>These details are optional and can be updated later from Profile.</Text><Input label="Payment QR HTTPS URL (optional)" autoCapitalize="none" value={form.paymentQrUrl} onChange={(v) => change('paymentQrUrl', v)} /><Input label="UPI ID (optional)" autoCapitalize="none" value={form.upiId} onChange={(v) => change('upiId', v)} /></Card> : null}
    {error ? <InlineError message={error} /> : null}{apiError ? <InlineError message={apiError} /> : null}
    <View style={styles.actions}>{step > 0 ? <Button label="Back" secondary disabled={pending} onPress={() => { setError(''); setStep((current) => Math.max(0, current - 1)); }} /> : null}<Button label={step < 2 ? 'Continue' : pending ? 'Completing…' : 'Complete onboarding'} disabled={pending} loading={step === 2 && pending} onPress={step < 2 ? next : submit} /></View>
  </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Card({ title, children }: { title: string; children: ReactNode }) { return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>; }
function Input({ label, value, onChange, multiline, autoCapitalize = 'words', keyboardType = 'default' }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; autoCapitalize?: 'none' | 'words' | 'characters'; keyboardType?: 'default' | 'email-address' | 'number-pad' }) { return <View style={styles.control}><Text style={styles.label}>{label}</Text><TextInput autoCapitalize={autoCapitalize} keyboardType={keyboardType} multiline={multiline} onChangeText={onChange} placeholderTextColor={colors.textTertiary} style={[styles.input, multiline && styles.multiline]} value={value} /></View>; }
function ReadOnly({ label, value }: { label: string; value: string }) { return <View style={styles.control}><Text style={styles.label}>{label}</Text><View style={[styles.input, styles.readOnly]}><Text style={styles.readOnlyText}>{value} ✓</Text></View></View>; }
function Button({ label, onPress, secondary, disabled, loading }: { label: string; onPress: () => void; secondary?: boolean; disabled?: boolean; loading?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, secondary && styles.secondary, (pressed || disabled) && styles.disabled]}>{loading ? <ActivityIndicator color={colors.textOnPrimary} /> : <Text style={[styles.buttonText, secondary && styles.secondaryText]}>{label}</Text>}</Pressable>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { flexGrow: 1, gap: spacing.lg, padding: spacing.lg, paddingBottom: spacing['4xl'] }, brand: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 11, letterSpacing: 1.2 }, heading: { color: colors.textPrimary, fontFamily: fontFamilies.headingBold, fontSize: 28 }, subtitle: { color: colors.textSecondary, fontFamily: fontFamilies.body, fontSize: 13 }, progress: { height: 8, overflow: 'hidden', backgroundColor: colors.surfaceMuted, borderRadius: radius.full }, progressFill: { height: '100%', backgroundColor: colors.primaryDark, borderRadius: radius.full }, card: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, cardTitle: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 20 }, control: { gap: spacing.xs }, label: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 13 }, input: { minHeight: touchTarget.min, justifyContent: 'center', paddingHorizontal: spacing.md, paddingVertical: spacing.sm, color: colors.textPrimary, backgroundColor: colors.background, borderColor: colors.borderStrong, borderRadius: radius.control, borderWidth: 1, fontFamily: fontFamilies.body, fontSize: 15 }, multiline: { minHeight: 88, textAlignVertical: 'top' }, readOnly: { backgroundColor: colors.surfaceMuted }, readOnlyText: { color: colors.textPrimary, fontFamily: fontFamilies.numbers, fontSize: 14 }, help: { color: colors.textSecondary, fontFamily: fontFamilies.body, fontSize: 13, lineHeight: 19 }, options: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, option: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.surfaceMuted, borderRadius: radius.chip }, optionSelected: { backgroundColor: colors.primaryDark }, optionText: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 12 }, optionTextSelected: { color: colors.textOnPrimary }, actions: { flexDirection: 'row', gap: spacing.sm }, button: { flex: 1, minHeight: 52, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.primaryDark, borderRadius: radius.control }, secondary: { backgroundColor: colors.surfaceMuted }, disabled: { opacity: 0.55 }, buttonText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 15 }, secondaryText: { color: colors.textPrimary } });
