import { useEffect } from 'react';
import type { Href } from 'expo-router';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { InlineError, LoadingState, MutationLoading, RetryState, StatusBadge } from '@/components/native/ScreenStates';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { useMarkMerchantNotificationRead, useMerchantNotification } from '@/features/merchantNotifications/hooks/useMerchantNotifications';
import { formatNotificationTime } from '@/features/merchantNotifications/mapper';
import { merchantNotificationError, relatedNotificationRoute } from '@/features/merchantNotifications/presentation';

export default function NotificationDetail() {
  const params = useLocalSearchParams<{ id?: string }>(); const id = typeof params.id === 'string' ? params.id : ''; const router = useRouter(); const query = useMerchantNotification(id); const read = useMarkMerchantNotificationRead();
  useEffect(() => { if (query.data && !query.data.isRead && !read.isPending) read.mutate(query.data.id); }, [query.data?.id, query.data?.isRead]);
  const related = query.data ? relatedNotificationRoute(query.data) : null;
  return <MerchantScreen title="Notification" showBack refreshing={query.isRefetching} onRefresh={() => void query.refetch()}>{query.isPending ? <LoadingState label="Loading notification..." /> : query.isError || !query.data ? <RetryState title="Could not load notification" message={merchantNotificationError(query.error)} onRetry={() => void query.refetch()} /> : <View style={styles.content}><View style={styles.heading}><Text style={styles.title}>{query.data.title}</Text><StatusBadge label={query.data.isRead ? 'Read' : 'Unread'} tone={query.data.isRead ? 'neutral' : 'warning'} /></View><Text style={styles.time}>{formatNotificationTime(query.data.createdAt)}</Text><View style={styles.message}><Text style={styles.body}>{query.data.body}</Text></View><View style={styles.metadata}><Field label="Type" value={query.data.type.replaceAll('_', ' ')} /><Field label="Created" value={formatNotificationTime(query.data.createdAt)} />{query.data.readAt ? <Field label="Read" value={formatNotificationTime(query.data.readAt)} /> : null}</View>{related ? <Pressable onPress={() => router.push(related as Href)} style={styles.action}><Text style={styles.actionText}>Open {query.data.relatedEntity?.type.toLowerCase()}</Text></Pressable> : null}{read.isPending ? <MutationLoading label="Marking notification read..." /> : null}{read.isError ? <InlineError message={merchantNotificationError(read.error)} /> : null}</View>}</MerchantScreen>;
}
function Field({ label, value }: { label: string; value: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: spacing.lg }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, title: { flex: 1, color: colors.textPrimary, fontFamily: fontFamilies.headingBold, fontSize: 24, lineHeight: 31 }, time: { color: colors.textTertiary, fontFamily: fontFamilies.body, fontSize: 12 }, message: { padding: spacing.xl, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, body: { color: colors.textPrimary, fontFamily: fontFamilies.body, fontSize: 15, lineHeight: 24 }, metadata: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderRadius: radius.card }, field: { gap: spacing.xxs }, label: { color: colors.textTertiary, fontFamily: fontFamilies.bodyMedium, fontSize: 11 }, value: { color: colors.textPrimary, fontFamily: fontFamilies.body, fontSize: 14 }, action: { minHeight: touchTarget.min, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primaryDark, borderRadius: radius.control }, actionText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 14 } });
