import { useState } from 'react';
import type { Href } from 'expo-router';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { MerchantNotificationDto } from '@/contracts/merchantNotification';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { EmptyState, InlineError, LoadingState, MutationLoading, RetryState } from '@/components/native/ScreenStates';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { useMarkAllMerchantNotificationsRead, useMerchantNotifications, useMerchantUnreadCount } from '@/features/merchantNotifications/hooks/useMerchantNotifications';
import { formatNotificationTime } from '@/features/merchantNotifications/mapper';
import { merchantNotificationError, notificationListParams, type MerchantNotificationFilter } from '@/features/merchantNotifications/presentation';
import { merchantRoutes } from '@/navigation/merchantRoutes';

export default function Notifications() {
  const router = useRouter(); const [page, setPage] = useState(1); const [filter, setFilter] = useState<MerchantNotificationFilter>('all'); const params = notificationListParams(page, filter); const list = useMerchantNotifications(params); const count = useMerchantUnreadCount(); const markAll = useMarkAllMerchantNotificationsRead();
  const chooseFilter = (next: MerchantNotificationFilter) => { setFilter(next); setPage(1); };
  return <MerchantScreen title="Notifications" subtitle="Real enquiry and visit updates" showBack refreshing={list.isRefetching} onRefresh={() => { void list.refetch(); void count.refetch(); }} action={(count.data?.count ?? 0) > 0 ? <Pressable disabled={markAll.isPending} onPress={() => markAll.mutate()} style={styles.headerAction}><Text style={styles.headerActionText}>{markAll.isPending ? 'Updating...' : 'Read all'}</Text></Pressable> : null}><View style={styles.filters}>{(['all', 'unread', 'read'] as const).map((item) => <Pressable key={item} onPress={() => chooseFilter(item)} style={[styles.chip, filter === item && styles.chipSelected]}><Text style={[styles.chipText, filter === item && styles.chipTextSelected]}>{item[0].toUpperCase() + item.slice(1)}{item === 'unread' && count.data ? ` (${count.data.count})` : ''}</Text></Pressable>)}</View>{markAll.isPending ? <MutationLoading label="Marking notifications read..." /> : null}{markAll.isError ? <InlineError message={merchantNotificationError(markAll.error)} /> : null}{list.isPending ? <LoadingState label="Loading notifications..." /> : list.isError ? <RetryState title="Could not load notifications" message={merchantNotificationError(list.error)} onRetry={() => void list.refetch()} /> : !list.data.items.length ? <EmptyState title="No notifications" message="You are all caught up. New alerts will appear here." /> : <View style={styles.list}>{list.data.items.map((notification) => <NotificationCard key={notification.id} notification={notification} onPress={() => router.push({ pathname: merchantRoutes.notificationDetail, params: { id: notification.id } } as Href)} />)}</View>}{list.data && list.data.meta.totalPages > 1 ? <View style={styles.pagination}><Pressable disabled={page === 1 || list.isFetching} onPress={() => setPage((value) => value - 1)} style={styles.pageButton}><Text style={styles.pageText}>Previous</Text></Pressable><Text style={styles.pageLabel}>Page {page} of {list.data.meta.totalPages}</Text><Pressable disabled={page >= list.data.meta.totalPages || list.isFetching} onPress={() => setPage((value) => value + 1)} style={styles.pageButton}><Text style={styles.pageText}>Next</Text></Pressable></View> : null}</MerchantScreen>;
}
function NotificationCard({ notification, onPress }: { notification: MerchantNotificationDto; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.card, !notification.isRead && styles.unread]}><View style={styles.cardHeading}><Text style={styles.title}>{notification.title}</Text>{!notification.isRead ? <View accessibilityLabel="Unread" style={styles.dot} /> : null}</View><Text style={styles.time}>{formatNotificationTime(notification.createdAt)}</Text><Text style={styles.body}>{notification.body}</Text><Text style={styles.type}>{notification.type.replaceAll('_', ' ')}</Text></Pressable>; }
const styles = StyleSheet.create({ headerAction: { minHeight: 36, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.primaryMuted, borderRadius: radius.control }, headerActionText: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 11 }, filters: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.lg }, chip: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.surfaceMuted, borderRadius: radius.chip }, chipSelected: { backgroundColor: colors.primaryDark }, chipText: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 12 }, chipTextSelected: { color: colors.textOnPrimary }, list: { gap: spacing.md }, card: { gap: spacing.xs, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1, opacity: 0.82 }, unread: { borderColor: colors.accent, opacity: 1 }, cardHeading: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, title: { flex: 1, color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 16 }, dot: { width: 10, height: 10, backgroundColor: colors.primaryDark, borderRadius: radius.full }, time: { color: colors.textTertiary, fontFamily: fontFamilies.body, fontSize: 11 }, body: { color: colors.textSecondary, fontFamily: fontFamilies.body, fontSize: 14, lineHeight: 21 }, type: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 10 }, pagination: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.md, marginTop: spacing.lg }, pageButton: { minHeight: touchTarget.min, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.primaryMuted, borderRadius: radius.control }, pageText: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 12 }, pageLabel: { color: colors.textSecondary, fontFamily: fontFamilies.body, fontSize: 12 } });
