import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { MerchantPg, PgAvailabilityInput } from '@/contracts/merchantPg';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { EmptyState, InlineError, LoadingState, MutationLoading, RetryState, SuccessFeedback } from '@/components/native/ScreenStates';
import { PgActionButton, PgStatusBadge, pgErrorMessage } from '@/components/native/pg/PgUi';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { canEditPg } from '@/features/merchantPgs/mapper';
import { useMerchantPgs, useUpdateMerchantPg } from '@/features/merchantPgs/hooks/useMerchantPgs';

export default function Availability() {
  const query = useMerchantPgs(); const [selectedId, setSelectedId] = useState('');
  useEffect(() => { if (!selectedId && query.data?.[0]) setSelectedId(query.data[0].id); }, [query.data, selectedId]);
  const selected = query.data?.find((pg) => pg.id === selectedId);
  return <MerchantScreen title="Availability" subtitle="Manage available beds by room type" refreshing={query.isRefetching} onRefresh={() => void query.refetch()}>{query.isPending ? <LoadingState label="Loading availability..." /> : query.isError ? <RetryState message={pgErrorMessage(query.error)} onRetry={() => void query.refetch()} /> : !query.data?.length ? <EmptyState title="No PGs yet" message="Create a PG before managing availability." /> : <View style={styles.content}><View style={styles.selector}>{query.data.map((pg) => <Pressable key={pg.id} onPress={() => setSelectedId(pg.id)} style={[styles.chip, pg.id === selectedId && styles.chipSelected]}><Text style={[styles.chipText, pg.id === selectedId && styles.chipTextSelected]}>{pg.name}</Text></Pressable>)}</View>{selected ? <AvailabilityEditor key={`${selected.id}-${selected.timestamps.updatedAt}`} pg={selected} /> : null}</View>}</MerchantScreen>;
}

function AvailabilityEditor({ pg }: { pg: MerchantPg }) {
  const update = useUpdateMerchantPg(pg.id); const [rows, setRows] = useState<PgAvailabilityInput[]>(() => pg.availability.map(({ roomType, totalBeds, availableBeds, monthlyRent }) => ({ roomType, totalBeds, availableBeds, monthlyRent })));
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const editable = canEditPg(pg);
  const save = () => { const invalid = rows.some((row) => !Number.isInteger(row.availableBeds) || row.availableBeds < 0 || row.availableBeds > row.totalBeds); if (invalid) { setError('Available beds must be a whole number between 0 and total beds.'); setSuccess(''); return; } update.mutate({ availability: rows }, { onSuccess: () => { setError(''); setSuccess('Availability updated.'); }, onError: (reason) => { setSuccess(''); setError(pgErrorMessage(reason)); } }); };
  return <View style={styles.card}><View style={styles.heading}><View style={styles.grow}><Text style={styles.title}>{pg.name}</Text><Text style={styles.note}>Availability can be edited only while the PG is Draft or Changes Required.</Text></View><PgStatusBadge status={pg.status} /></View>{!rows.length ? <EmptyState title="No availability rows" message="Add availability while editing this PG." /> : rows.map((row, index) => <View key={`${row.roomType}-${index}`} style={styles.row}><View style={styles.grow}><Text style={styles.rowTitle}>{row.roomType}</Text><Text style={styles.note}>{row.totalBeds} total beds · ₹{row.monthlyRent}</Text></View><TextInput accessibilityLabel={`Available beds for ${row.roomType}`} editable={editable} keyboardType="number-pad" value={String(row.availableBeds)} onChangeText={(text) => setRows((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, availableBeds: Number(text.replace(/\D/g, '')) || 0 } : item))} style={[styles.input, !editable && styles.disabled]} /></View>)}{error ? <InlineError message={error} /> : null}{success ? <SuccessFeedback message={success} /> : null}{update.isPending ? <MutationLoading label="Updating availability..." /> : null}{rows.length && editable ? <PgActionButton label="Save availability" disabled={update.isPending} onPress={save} /> : null}</View>;
}

const styles = StyleSheet.create({ content: { gap: spacing.lg }, selector: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, chip: { minHeight: touchTarget.min, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.surfaceMuted, borderRadius: radius.chip }, chipSelected: { backgroundColor: colors.primaryDark }, chipText: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 13 }, chipTextSelected: { color: colors.textOnPrimary }, card: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, grow: { flex: 1 }, title: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 19 }, note: { color: colors.textSecondary, fontFamily: fontFamilies.body, fontSize: 12, lineHeight: 18 }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.md, borderBottomColor: colors.divider, borderBottomWidth: 1 }, rowTitle: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 14 }, input: { width: 76, minHeight: touchTarget.min, textAlign: 'center', color: colors.textPrimary, backgroundColor: colors.background, borderColor: colors.borderStrong, borderRadius: radius.control, borderWidth: 1, fontFamily: fontFamilies.bodySemiBold, fontSize: 15 }, disabled: { opacity: 0.55 } });
