import { useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { MerchantVisitStatus, VisitRescheduleInput } from '@/contracts/merchantVisit';
import { InlineError } from '@/components/native/ScreenStates';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { allowedVisitActions, type MerchantVisitAction } from '@/features/merchantVisits/transitions';
import { validateReschedule } from '@/features/merchantVisits/validation';

export const visitActionLabel = (action: MerchantVisitAction) => action === 'noShow' ? 'No-show' : action[0].toUpperCase() + action.slice(1);
export function VisitActions({ status, busy, onAction }: { status: MerchantVisitStatus; busy: boolean; onAction: (action: MerchantVisitAction) => void }) { return <View style={styles.actions}>{allowedVisitActions(status).map((action) => <Pressable disabled={busy} key={action} onPress={() => onAction(action)} style={[styles.action, busy && styles.disabled]}><Text style={styles.actionText}>{visitActionLabel(action)}</Text></Pressable>)}</View>; }

export function RescheduleVisitModal({ visible, busy, onClose, onSubmit }: { visible: boolean; busy: boolean; onClose: () => void; onSubmit: (input: VisitRescheduleInput) => void }) {
  const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [note, setNote] = useState(''); const [error, setError] = useState('');
  const submit = () => { const input = { visitDate: date, visitTime: time, timeZone: 'Asia/Kolkata', ...(note.trim() ? { note: note.trim() } : {}) }; const problem = validateReschedule(input); if (problem) { setError(problem); return; } setError(''); onSubmit(input); };
  return <Modal animationType="slide" transparent visible={visible} onRequestClose={onClose}><View style={styles.overlay}><View style={styles.dialog}><Text style={styles.title}>Reschedule visit</Text><Text style={styles.help}>Timezone: Asia/Kolkata</Text><Field label="Date (YYYY-MM-DD)" value={date} onChange={setDate} placeholder="2026-12-10" /><Field label="Time (24-hour HH:mm)" value={time} onChange={setTime} placeholder="10:30" /><Field label="Optional note" value={note} onChange={setNote} placeholder="Add a note" multiline />{error ? <InlineError message={error} /> : null}<View style={styles.footer}><Pressable disabled={busy} onPress={onClose} style={styles.secondary}><Text style={styles.secondaryText}>Cancel</Text></Pressable><Pressable disabled={busy} onPress={submit} style={[styles.primary, busy && styles.disabled]}><Text style={styles.primaryText}>{busy ? 'Rescheduling...' : 'Request reschedule'}</Text></Pressable></View></View></View></Modal>;
}
function Field({ label, value, onChange, placeholder, multiline }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; multiline?: boolean }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput autoCapitalize="none" multiline={multiline} placeholder={placeholder} placeholderTextColor={colors.textTertiary} value={value} onChangeText={onChange} style={[styles.input, multiline && styles.multiline]} /></View>; }
const styles = StyleSheet.create({ actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, action: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.primaryMuted, borderRadius: radius.control }, actionText: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 12 }, disabled: { opacity: 0.5 }, overlay: { flex: 1, justifyContent: 'center', padding: spacing.xl, backgroundColor: colors.overlay }, dialog: { gap: spacing.md, padding: spacing.xl, backgroundColor: colors.surface, borderRadius: radius.sheet }, title: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 21 }, help: { color: colors.textSecondary, fontFamily: fontFamilies.body, fontSize: 12 }, field: { gap: spacing.xs }, label: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 12 }, input: { minHeight: touchTarget.min, paddingHorizontal: spacing.md, color: colors.textPrimary, backgroundColor: colors.background, borderColor: colors.borderStrong, borderRadius: radius.control, borderWidth: 1, fontFamily: fontFamilies.body }, multiline: { minHeight: 88, paddingTop: spacing.md, textAlignVertical: 'top' }, footer: { flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.sm }, primary: { minHeight: touchTarget.min, justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.primaryDark, borderRadius: radius.control }, primaryText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold }, secondary: { minHeight: touchTarget.min, justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.surfaceMuted, borderRadius: radius.control }, secondaryText: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold } });
