import { useMemo, useState } from 'react';
import { Building2, MessageSquare, RefreshCw, X } from 'lucide-react';
import { ApiError } from '../../api/errors';
import type { MerchantEnquiryStatus } from '../../contracts/merchantEnquiry';
import { useMerchantEnquiries,useMerchantEnquiry,useUpdateMerchantEnquiry } from '../../features/merchantEnquiries/hooks/useMerchantEnquiries';
import { displayEnquiryStatus,formatEnquiryDate } from '../../features/merchantEnquiries/mapper';
import { allowedEnquiryTransitions } from '../../features/merchantEnquiries/transitions';

const statuses: Array<'ALL'|MerchantEnquiryStatus>=['ALL','NEW','CONTACTED','VISIT_SCHEDULED','CLOSED','CANCELLED','REJECTED','NO_RESPONSE'];
const message=(error:unknown)=>error instanceof ApiError?(error.status===409?'The enquiry changed elsewhere. The latest state has been refreshed.':error.message):'Unable to load enquiries. Please try again.';
const Badge=({status}:{status:MerchantEnquiryStatus})=><span className="px-2.5 py-1 rounded-full text-[11px] font-bold bg-[#E8F1FA] text-[#527DAF] border border-[#6F9BD1]/30">{displayEnquiryStatus(status)}</span>;
const Field=({label,value}:{label:string;value:string})=><div><span className="block text-[11px] text-[#6B7280]">{label}</span><span className="font-semibold text-[#2F3A35]">{value}</span></div>;
export const EnquiryState=({title,text,retry}:{title:string;text:string;retry?:()=>void})=><div className="bg-white border border-[#EAE8E4] rounded-[24px] p-12 text-center"><MessageSquare className="w-10 h-10 mx-auto text-[#9CA3AF]"/><h3 className="font-bold mt-3">{title}</h3><p className="text-xs text-[#6B7280] mt-1">{text}</p>{retry&&<button onClick={retry} className="mt-4 px-4 py-2 rounded-xl bg-[#7B9D8A] text-white text-xs font-semibold mx-auto flex gap-1"><RefreshCw className="w-4 h-4"/>Retry</button>}</div>;

export function EnquiriesView(){
 const list=useMerchantEnquiries(),update=useUpdateMerchantEnquiry();
 const[filter,setFilter]=useState<(typeof statuses)[number]>('ALL'),[search,setSearch]=useState(''),[id,setId]=useState<string>(),[success,setSuccess]=useState('');
 const detail=useMerchantEnquiry(id);
 const items=useMemo(()=>(list.data??[]).filter(e=>(filter==='ALL'||e.status===filter)&&(!search.trim()||[e.user.name,e.user.phone,e.pg.name].some(v=>v.toLowerCase().includes(search.toLowerCase())))),[list.data,filter,search]);
 const change=(enquiryId:string,status:MerchantEnquiryStatus)=>{setSuccess('');update.mutate({id:enquiryId,status},{onSuccess:()=>setSuccess(`Enquiry marked ${displayEnquiryStatus(status)}.`)})};
 return <div className="space-y-6 animate-in fade-in duration-200">
  <div><h1 className="text-2xl font-bold text-[#2F3A35]">Prospective Tenant Enquiries</h1><p className="text-xs text-[#6B7280]">Review tenant interest and keep each enquiry status current.</p></div>
  <div className="bg-white border rounded-[24px] p-4 flex flex-col md:flex-row gap-3 justify-between"><div className="flex gap-1.5 overflow-x-auto">{statuses.map(s=><button key={s} onClick={()=>setFilter(s)} className={`px-3 py-1.5 rounded-full text-xs whitespace-nowrap ${filter===s?'bg-[#7B9D8A] text-white':'border'}`}>{s==='ALL'?'All':displayEnquiryStatus(s)}</button>)}</div><input aria-label="Search enquiries" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tenant, phone or PG..." className="px-3.5 py-1.5 text-xs border rounded-[18px]"/></div>
  {success&&<p role="status" className="p-3 bg-[#E8F5EC] text-[#2E7D32] rounded-xl">{success}</p>}
  {update.isError&&<p role="alert" className="p-3 bg-[#FDECEC] text-[#B33A3A] rounded-xl">{message(update.error)}</p>}
  {list.isPending?<p className="p-12 text-center text-sm text-[#6B7280]">Loading enquiries…</p>:list.isError?<EnquiryState title="Could not load enquiries" text={message(list.error)} retry={()=>void list.refetch()}/>:items.length===0?<EnquiryState title="No enquiries found" text={(list.data?.length??0)===0?'New tenant enquiries will appear here.':'No enquiries match this filter.'}/>:<div className="grid md:grid-cols-2 gap-4">{items.map(e=><article key={e.id} className="bg-white border border-[#EAE8E4] rounded-[24px] p-5 space-y-4"><div className="flex justify-between gap-2"><div><h3 className="font-bold">{e.user.name}</h3><p className="text-xs text-[#7B9D8A] flex gap-1"><Building2 className="w-4 h-4"/>{e.pg.name}</p></div><Badge status={e.status}/></div><div className="grid grid-cols-2 gap-2 p-3 border rounded-2xl text-xs"><Field label="Room" value={e.details.roomType??'Not specified'}/><Field label="Move-in" value={formatEnquiryDate(e.details.moveInDate)}/><Field label="Created" value={formatEnquiryDate(e.createdAt)}/><Field label="Phone" value={e.user.phone}/></div><div className="flex flex-wrap gap-2"><button onClick={()=>setId(e.id)} className="px-3 py-1.5 rounded-xl bg-[#7B9D8A] text-white text-xs">View details</button>{allowedEnquiryTransitions(e.status).map(s=><button disabled={update.isPending} key={s} onClick={()=>change(e.id,s)} className="px-3 py-1.5 rounded-xl border text-xs disabled:opacity-50">{update.isPending&&update.variables?.id===e.id?'Updating…':displayEnquiryStatus(s)}</button>)}</div></article>)}</div>}
  {id&&<div className="fixed inset-0 z-50 bg-black/35 p-4 flex items-center justify-center" onMouseDown={()=>setId(undefined)}><section className="w-full max-w-xl bg-white rounded-[24px] p-6 space-y-4" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-bold">Enquiry details</h2><button aria-label="Close details" onClick={()=>setId(undefined)}><X/></button></div>{detail.isPending?<p>Loading details…</p>:detail.isError?<EnquiryState title="Could not load enquiry" text={message(detail.error)} retry={()=>void detail.refetch()}/>:detail.data?<><div className="flex justify-between"><div><h3 className="font-bold">{detail.data.user.name}</h3><p className="text-xs text-[#7B9D8A]">{detail.data.pg.name}</p></div><Badge status={detail.data.status}/></div><div className="grid grid-cols-2 gap-3 text-sm"><Field label="Phone" value={detail.data.user.phone}/><Field label="Email" value={detail.data.user.email??'Not provided'}/><Field label="Room" value={detail.data.details.roomType??'Not specified'}/><Field label="Move-in" value={formatEnquiryDate(detail.data.details.moveInDate)}/><Field label="Created" value={formatEnquiryDate(detail.data.createdAt)}/><Field label="Updated" value={formatEnquiryDate(detail.data.updatedAt)}/></div><div className="p-3 bg-[#FAF8F4] rounded-xl text-sm"><b>Message</b><p>{detail.data.details.message??'No message provided.'}</p></div></>:null}</section></div>}
 </div>
}
