import{useState}from'react';import{Bell,CheckCheck,ChevronLeft,ChevronRight,RefreshCw,X}from'lucide-react';import{ApiError}from'../../api/errors';import{useMarkAllMerchantNotificationsRead,useMarkMerchantNotificationRead,useMerchantNotification,useMerchantNotifications,useMerchantUnreadCount}from'../../features/merchantNotifications/hooks/useMerchantNotifications';import{formatNotificationTime}from'../../features/merchantNotifications/mapper';
const errorText=(e:unknown)=>e instanceof ApiError?e.message:'Unable to load notifications. Please try again.';
const State=({title,text,retry}:{title:string;text:string;retry?:()=>void})=><div className="bg-white border rounded-[24px] p-12 text-center"><Bell className="w-10 h-10 text-[#9CA3AF] mx-auto"/><h3 className="font-bold mt-3">{title}</h3><p className="text-xs text-[#6B7280]">{text}</p>{retry&&<button onClick={retry} className="mt-4 px-4 py-2 bg-[#7B9D8A] text-white rounded-xl text-xs mx-auto flex gap-1"><RefreshCw className="w-4"/>Retry</button>}</div>;
export function NotificationsView({onNavigate}:{onNavigate?:(target:'enquiries'|'visits')=>void}){const[page,setPage]=useState(1),[unread,setUnread]=useState<boolean|undefined>(),[id,setId]=useState<string>();const params={page,limit:20,...(unread===undefined?{}:{unread})},list=useMerchantNotifications(params),count=useMerchantUnreadCount(),detail=useMerchantNotification(id),read=useMarkMerchantNotificationRead(),all=useMarkAllMerchantNotificationsRead();const open=(notificationId:string,isRead:boolean)=>{setId(notificationId);if(!isRead)read.mutate(notificationId)};
return <div className="space-y-6 max-w-4xl mx-auto"><div className="flex justify-between gap-4"><div><h1 className="text-2xl font-bold">Merchant Notifications</h1><p className="text-xs text-[#6B7280]">Real enquiry and visit updates from StayNest.</p></div>{(count.data?.count??0)>0&&<button disabled={all.isPending} onClick={()=>all.mutate()} className="px-3.5 py-2 rounded-2xl bg-[#DDE9E0] text-[#7B9D8A] text-xs font-semibold disabled:opacity-50 flex gap-1"><CheckCheck className="w-4"/>{all.isPending?'Updating…':'Mark all read'}</button>}</div>
<div className="bg-white border rounded-[24px] p-3 flex gap-2">{[['All',undefined],['Unread',true],['Read',false]].map(([label,value])=><button key={String(label)} onClick={()=>{setUnread(value as boolean|undefined);setPage(1)}} className={`px-4 py-1.5 rounded-full text-xs ${unread===value?'bg-[#7B9D8A] text-white':'border'}`}>{label}{label==='Unread'&&count.data?` (${count.data.count})`:''}</button>)}</div>
{(read.isError||all.isError)&&<p role="alert" className="p-3 bg-[#FDECEC] text-[#B33A3A] rounded-xl">{errorText(read.error??all.error)}</p>}
{list.isPending?<p className="p-12 text-center">Loading notifications…</p>:list.isError?<State title="Could not load notifications" text={errorText(list.error)} retry={()=>void list.refetch()}/>:list.data.items.length===0?<State title="No notifications" text="You are all caught up. New alerts will appear here."/>:<div className="space-y-3">{list.data.items.map(n=><button key={n.id} onClick={()=>open(n.id,n.isRead)} className={`w-full text-left p-4 rounded-[24px] border flex gap-3 ${n.isRead?'bg-[#FFFFFF] border-[#EAE8E4] opacity-80':'bg-white border-[#D8C29B] shadow-soft-sm'}`}><Bell className="w-5 h-5 text-[#6F9BD1] shrink-0"/><div className="flex-1"><div className="flex justify-between gap-2"><h3 className="text-sm font-bold">{n.title}</h3><time className="text-[11px] text-[#6B7280]">{formatNotificationTime(n.createdAt)}</time></div><p className="text-xs text-[#6B7280] mt-1">{n.body}</p><span className="text-[10px] text-[#7B9D8A]">{n.type.replaceAll('_',' ')}</span></div>{!n.isRead&&<span className="w-2.5 h-2.5 rounded-full bg-[#7B9D8A]"/>}</button>)}</div>}
{list.data&&list.data.meta.totalPages>1&&<div className="flex justify-center items-center gap-3"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button><span className="text-xs">Page {page} of {list.data.meta.totalPages}</span><button disabled={page>=list.data.meta.totalPages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div>}
{id&&<div className="fixed inset-0 z-50 bg-black/35 flex items-center justify-center p-4" onMouseDown={()=>setId(undefined)}><section className="bg-white rounded-[24px] p-6 max-w-lg w-full space-y-4" onMouseDown={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="font-bold text-xl">Notification</h2><button onClick={()=>setId(undefined)}><X/></button></div>{detail.isPending?<p>Loading notification…</p>:detail.isError?<State title="Could not load notification" text={errorText(detail.error)} retry={()=>void detail.refetch()}/>:detail.data?<><div><h3 className="font-bold">{detail.data.title}</h3><time className="text-xs text-[#6B7280]">{formatNotificationTime(detail.data.createdAt)}</time></div><p className="text-sm">{detail.data.body}</p>{detail.data.relatedEntity&&onNavigate&&<button onClick={()=>{onNavigate(detail.data!.relatedEntity!.type==='ENQUIRY'?'enquiries':'visits');setId(undefined)}} className="px-4 py-2 bg-[#7B9D8A] text-white rounded-xl text-xs">Open {detail.data.relatedEntity.type.toLowerCase()}</button>}</>:null}</section></div>}</div>}
