import { useEffect, useMemo, useState } from 'react';
import type { Href } from 'expo-router';
import { useRouter } from 'expo-router';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { MerchantResidentStatus } from '@/contracts/merchantResident';
import { merchantResidentStatuses } from '@/contracts/merchantResident';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { EmptyState, LoadingState, RetryState } from '@/components/native/ScreenStates';
import { ResidentCard } from '@/components/native/residents/ResidentUi';
import { colors, fontFamilies, radius, spacing } from '@/design-system';
import { useMerchantPgs } from '@/features/merchantPgs/hooks/useMerchantPgs';
import { merchantResidentError } from '@/features/merchantResidents/presentation';
import { merchantResidentKeys, useMerchantResidents } from '@/features/merchantResidents/hooks/useMerchantResidents';
import { queryClient } from '@/query/client';

const limit=20;
export default function Residents(){const router=useRouter();const[search,setSearch]=useState('');const[debounced,setDebounced]=useState('');const[status,setStatus]=useState<MerchantResidentStatus|undefined>();const[pgId,setPgId]=useState<string|undefined>();useEffect(()=>{const timer=setTimeout(()=>setDebounced(search.trim()),350);return()=>clearTimeout(timer)},[search]);const params=useMemo(()=>({limit,status,pgId,search:debounced||undefined}),[status,pgId,debounced]);const query=useMerchantResidents(params);const pgs=useMerchantPgs();const items=query.data?.pages.flatMap(page=>page.items)??[];const refresh=()=>queryClient.resetQueries({queryKey:merchantResidentKeys.list(params),exact:true});return <MerchantScreen title="Residents" subtitle="Stays, rent days, and reminder preferences" showBack refreshing={query.isRefetching&&!query.isFetchingNextPage} onRefresh={()=>void refresh()}><View style={styles.search}><TextInput autoCapitalize="none" placeholder="Search resident, room or PG" placeholderTextColor={colors.textTertiary} value={search} onChangeText={setSearch} style={styles.input}/></View><Text style={styles.filterTitle}>Status</Text><View style={styles.chips}><Chip label="All" active={!status} onPress={()=>setStatus(undefined)}/>{merchantResidentStatuses.map(value=><Chip key={value} label={value} active={status===value} onPress={()=>setStatus(value)}/>)}</View><Text style={styles.filterTitle}>Property</Text><View style={styles.chips}><Chip label="All PGs" active={!pgId} onPress={()=>setPgId(undefined)}/>{(pgs.data??[]).map(pg=><Chip key={pg.id} label={pg.name} active={pgId===pg.id} onPress={()=>setPgId(pg.id)}/>)}</View>{pgs.isError?<Text style={styles.filterError}>PG filters could not be loaded. Resident results remain available.</Text>:null}{query.isPending?<LoadingState label="Loading residents…"/>:query.isError?<RetryState title="Residents could not be loaded" message={merchantResidentError(query.error)} onRetry={()=>void query.refetch()}/>:!items.length?<EmptyState title="No residents found" message={debounced||status||pgId?'No residents match the current search and filters.':'Residents will appear here when they are available.'}/>:<View style={styles.list}>{items.map(resident=><ResidentCard key={resident.id} resident={resident} onPress={()=>router.push({pathname:'/(merchant)/residents/[id]',params:{id:resident.id}} as unknown as Href)}/>)}</View>}{query.hasNextPage?<Pressable disabled={query.isFetchingNextPage} onPress={()=>void query.fetchNextPage()} style={styles.more}>{query.isFetchingNextPage?<ActivityIndicator color={colors.primaryDark}/>:<Text style={styles.moreText}>Load more residents</Text>}</Pressable>:null}</MerchantScreen>}
function Chip({label,active,onPress}:{label:string;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} style={[styles.chip,active&&styles.chipActive]}><Text numberOfLines={1} style={[styles.chipText,active&&styles.chipTextActive]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({search:{marginBottom:spacing.md},input:{minHeight:48,paddingHorizontal:spacing.md,color:colors.textPrimary,backgroundColor:colors.surface,borderColor:colors.borderStrong,borderWidth:1,borderRadius:radius.control,fontFamily:fontFamilies.body,fontSize:14},filterTitle:{marginTop:spacing.sm,marginBottom:spacing.sm,color:colors.textSecondary,fontFamily:fontFamilies.bodySemiBold,fontSize:12},chips:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm,marginBottom:spacing.md},chip:{maxWidth:'100%',minHeight:38,justifyContent:'center',paddingHorizontal:spacing.md,backgroundColor:colors.surfaceMuted,borderRadius:radius.chip},chipActive:{backgroundColor:colors.primaryDark},chipText:{color:colors.textSecondary,fontFamily:fontFamilies.bodyMedium,fontSize:12},chipTextActive:{color:colors.textOnPrimary},filterError:{marginBottom:spacing.md,color:colors.error,fontFamily:fontFamilies.body,fontSize:12},list:{gap:spacing.md},more:{minHeight:48,alignItems:'center',justifyContent:'center',marginTop:spacing.lg,backgroundColor:colors.primaryMuted,borderRadius:radius.control},moreText:{color:colors.primaryDark,fontFamily:fontFamilies.bodySemiBold,fontSize:14}});
