import { useState } from 'react';
import { useLocalSearchParams } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { MerchantEnquiryStatus } from '@/contracts/merchantEnquiry';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { ConfirmationAction, InlineError, LoadingState, MutationLoading, RetryState, StatusBadge, SuccessFeedback } from '@/components/native/ScreenStates';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { useMerchantEnquiry, useUpdateMerchantEnquiry } from '@/features/merchantEnquiries/hooks/useMerchantEnquiries';
import { displayEnquiryStatus, formatEnquiryDate } from '@/features/merchantEnquiries/mapper';
import { merchantEnquiryError } from '@/features/merchantEnquiries/presentation';
import { allowedEnquiryTransitions } from '@/features/merchantEnquiries/transitions';

export default function EnquiryDetail() {
  const params = useLocalSearchParams<{ id?: string }>(); const id = typeof params.id === 'string' ? params.id : ''; const query = useMerchantEnquiry(id); const update = useUpdateMerchantEnquiry();
  const [pending, setPending] = useState<MerchantEnquiryStatus | null>(null); const [success, setSuccess] = useState('');
  const change = () => { if (!pending) return; update.mutate({ id, status: pending }, { onSuccess: () => { setSuccess(`Enquiry marked ${displayEnquiryStatus(pending)}.`); setPending(null); }, onError: () => setPending(null) }); };
  return <MerchantScreen title="Enquiry Detail" showBack refreshing={query.isRefetching} onRefresh={() => void query.refetch()}>{query.isPending ? <LoadingState label="Loading enquiry details..." /> : query.isError || !query.data ? <RetryState title="Could not load enquiry" message={merchantEnquiryError(query.error)} onRetry={() => void query.refetch()} /> : <View style={styles.content}><View style={styles.heading}><View style={styles.grow}><Text style={styles.name}>{query.data.user.name}</Text><Text style={styles.pg}>{query.data.pg.name}</Text></View><StatusBadge label={displayEnquiryStatus(query.data.status)} tone={query.data.status === 'NEW' ? 'warning' : query.data.status === 'CLOSED' ? 'success' : ['CANCELLED', 'REJECTED', 'NO_RESPONSE'].includes(query.data.status) ? 'error' : 'neutral'} /></View><Section title="Tenant"><Field label="Phone" value={query.data.user.phone} /><Field label="Email" value={query.data.user.email ?? 'Not provided'} /></Section><Section title="PG"><Field label="Property" value={query.data.pg.name} /><Field label="Address" value={[query.data.pg.location.address, query.data.pg.location.locality, query.data.pg.location.city].filter(Boolean).join(', ')} /></Section><Section title="Enquiry"><Field label="Room" value={query.data.details.roomType ?? 'Not specified'} /><Field label="Move-in" value={formatEnquiryDate(query.data.details.moveInDate)} /><Field label="Created" value={formatEnquiryDate(query.data.createdAt)} /><Field label="Updated" value={formatEnquiryDate(query.data.updatedAt)} /><View style={styles.message}><Text style={styles.label}>Message</Text><Text style={styles.value}>{query.data.details.message ?? 'No message provided.'}</Text></View></Section>{allowedEnquiryTransitions(query.data.status).length ? <Section title="Actions"><View style={styles.actions}>{allowedEnquiryTransitions(query.data.status).map((status) => <Pressable disabled={update.isPending} key={status} onPress={() => { setSuccess(''); setPending(status); }} style={[styles.action, update.isPending && styles.disabled]}><Text style={styles.actionText}>{displayEnquiryStatus(status)}</Text></Pressable>)}</View></Section> : null}{success ? <SuccessFeedback message={success} /> : null}{update.isError ? <InlineError message={merchantEnquiryError(update.error)} /> : null}{update.isPending ? <MutationLoading label="Updating enquiry..." /> : null}</View>}<ConfirmationAction visible={Boolean(pending)} title="Update enquiry status?" message={`Change this enquiry to ${pending ? displayEnquiryStatus(pending) : ''}?`} confirmLabel="Update" busy={update.isPending} onCancel={() => setPending(null)} onConfirm={change} /></MerchantScreen>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>; }
function Field({ label, value }: { label: string; value: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { gap: spacing.lg }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.md }, grow: { flex: 1 }, name: { color: colors.textPrimary, fontFamily: fontFamilies.headingBold, fontSize: 25 }, pg: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 14 }, section: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, sectionTitle: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 17 }, field: { gap: spacing.xxs }, label: { color: colors.textTertiary, fontFamily: fontFamilies.bodyMedium, fontSize: 11 }, value: { color: colors.textPrimary, fontFamily: fontFamilies.body, fontSize: 14, lineHeight: 21 }, message: { gap: spacing.xs, padding: spacing.md, backgroundColor: colors.background, borderRadius: radius.lg }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, action: { minHeight: touchTarget.min, justifyContent: 'center', paddingHorizontal: spacing.lg, backgroundColor: colors.primaryDark, borderRadius: radius.control }, actionText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 13 }, disabled: { opacity: 0.5 } });
