import type { ReactNode } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { MerchantResidentDto } from '@/contracts/merchantResident';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { residentRentLabel, residentRoomLabel, residentStatusTone } from '@/features/merchantResidents/presentation';
import { StatusBadge } from '@/components/native/ScreenStates';

export function ResidentCard({ resident, onPress }: { resident: MerchantResidentDto; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[styles.card,pressed&&styles.pressed]}><View style={styles.heading}><View style={styles.grow}><Text style={styles.name}>{resident.resident.name}</Text><Text style={styles.phone}>{resident.resident.phone} · {resident.publicId}</Text></View><StatusBadge label={resident.stay.status} tone={residentStatusTone(resident.stay.status)} /></View><Field label="PG" value={resident.pg.name}/><Field label="Room" value={residentRoomLabel(resident)}/><View style={styles.row}><Field label="Joined" value={resident.stay.joinedDate}/><Field label="Rent" value={residentRentLabel(resident)}/></View><View style={styles.row}><Field label="Payment day" value={`Day ${resident.rent.paymentDay}`}/><Field label="SMS reminders" value={resident.rent.smsReminders?'On':'Off'}/></View></Pressable>; }
export function Section({title,children}:{title:string;children:ReactNode}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{children}</View>}
export function Field({label,value}:{label:string;value:string|null}){return <View style={styles.field}><Text style={styles.fieldLabel}>{label}</Text><Text style={[styles.fieldValue,!value&&styles.empty]}>{value||'Not provided'}</Text></View>}
const styles=StyleSheet.create({card:{gap:spacing.md,padding:spacing.lg,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radius.card},pressed:{opacity:.7},heading:{flexDirection:'row',gap:spacing.sm,alignItems:'flex-start'},grow:{flex:1},name:{color:colors.textPrimary,fontFamily:fontFamilies.heading,fontSize:17},phone:{marginTop:spacing.xs,color:colors.textSecondary,fontFamily:fontFamilies.numbersRegular,fontSize:12},row:{flexDirection:'row',gap:spacing.md},field:{flex:1,gap:spacing.xxs},fieldLabel:{color:colors.textTertiary,fontFamily:fontFamilies.bodyMedium,fontSize:11},fieldValue:{color:colors.textPrimary,fontFamily:fontFamilies.bodyMedium,fontSize:13,lineHeight:18},empty:{color:colors.textTertiary,fontStyle:'italic'},section:{gap:spacing.md,padding:spacing.lg,backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radius.card},sectionTitle:{color:colors.textPrimary,fontFamily:fontFamilies.heading,fontSize:18}});
