import { useMemo, useState } from 'react';
import type { Href } from 'expo-router';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { MerchantEnquiry, MerchantEnquiryStatus } from '@/contracts/merchantEnquiry';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { ConfirmationAction, EmptyState, InlineError, LoadingState, MutationLoading, RetryState, StatusBadge, SuccessFeedback } from '@/components/native/ScreenStates';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { displayEnquiryStatus, formatEnquiryDate } from '@/features/merchantEnquiries/mapper';
import { useMerchantEnquiries, useUpdateMerchantEnquiry } from '@/features/merchantEnquiries/hooks/useMerchantEnquiries';
import { allowedEnquiryTransitions } from '@/features/merchantEnquiries/transitions';
import { filterMerchantEnquiries, merchantEnquiryError, merchantEnquiryFilters, type MerchantEnquiryFilter } from '@/features/merchantEnquiries/presentation';
import { merchantRoutes } from '@/navigation/merchantRoutes';

export default function MerchantEnquiries() {
  const router = useRouter(); const query = useMerchantEnquiries(); const update = useUpdateMerchantEnquiry();
  const [filter, setFilter] = useState<MerchantEnquiryFilter>('ALL'); const [search, setSearch] = useState(''); const [pending, setPending] = useState<{ id: string; status: MerchantEnquiryStatus } | null>(null); const [success, setSuccess] = useState('');
  const items = useMemo(() => filterMerchantEnquiries(query.data ?? [], filter, search), [query.data, filter, search]);
  const change = () => { if (!pending) return; update.mutate(pending, { onSuccess: () => { setSuccess(`Enquiry marked ${displayEnquiryStatus(pending.status)}.`); setPending(null); }, onError: () => setPending(null) }); };
  return <MerchantScreen title="Enquiries" subtitle="Prospective tenant enquiries" refreshing={query.isRefetching} onRefresh={() => void query.refetch()}>
    <View style={styles.controls}><View style={styles.filters}>{merchantEnquiryFilters.map((status) => <Pressable key={status} onPress={() => setFilter(status)} style={[styles.chip, filter === status && styles.chipSelected]}><Text style={[styles.chipText, filter === status && styles.chipTextSelected]}>{status === 'ALL' ? 'All' : displayEnquiryStatus(status)}</Text></Pressable>)}</View><TextInput accessibilityLabel="Search enquiries" placeholder="Search tenant, phone or PG..." placeholderTextColor={colors.textTertiary} value={search} onChangeText={setSearch} style={styles.search} /></View>
    {success ? <SuccessFeedback message={success} /> : null}{update.isError ? <InlineError message={merchantEnquiryError(update.error)} /> : null}{update.isPending ? <MutationLoading label="Updating enquiry..." /> : null}
    {query.isPending ? <LoadingState label="Loading enquiries..." /> : query.isError ? <RetryState title="Could not load enquiries" message={merchantEnquiryError(query.error)} onRetry={() => void query.refetch()} /> : !items.length ? <EmptyState title="No enquiries found" message={!query.data?.length ? 'New tenant enquiries will appear here.' : 'No enquiries match this filter.'} /> : <View style={styles.list}>{items.map((enquiry) => <EnquiryCard key={enquiry.id} enquiry={enquiry} busy={update.isPending} onView={() => router.push({ pathname: merchantRoutes.enquiryDetail, params: { id: enquiry.id } } as Href)} onTransition={(status) => { setSuccess(''); setPending({ id: enquiry.id, status }); }} />)}</View>}
    <ConfirmationAction visible={Boolean(pending)} title="Update enquiry status?" message={`Change this enquiry to ${pending ? displayEnquiryStatus(pending.status) : ''}?`} confirmLabel="Update" busy={update.isPending} onCancel={() => setPending(null)} onConfirm={change} />
  </MerchantScreen>;
}

function EnquiryCard({ enquiry, busy, onView, onTransition }: { enquiry: MerchantEnquiry; busy: boolean; onView: () => void; onTransition: (status: MerchantEnquiryStatus) => void }) {
  return <View style={styles.card}><View style={styles.heading}><View style={styles.grow}><Text style={styles.name}>{enquiry.user.name}</Text><Text style={styles.pg}>{enquiry.pg.name}</Text></View><StatusBadge label={displayEnquiryStatus(enquiry.status)} tone={enquiry.status === 'NEW' ? 'warning' : enquiry.status === 'CLOSED' ? 'success' : ['CANCELLED', 'REJECTED', 'NO_RESPONSE'].includes(enquiry.status) ? 'error' : 'neutral'} /></View><View style={styles.fields}><Field label="Room" value={enquiry.details.roomType ?? 'Not specified'} /><Field label="Move-in" value={formatEnquiryDate(enquiry.details.moveInDate)} /><Field label="Created" value={formatEnquiryDate(enquiry.createdAt)} /><Field label="Phone" value={enquiry.user.phone} /></View><Pressable onPress={onView} style={styles.primary}><Text style={styles.primaryText}>View details</Text></Pressable><View style={styles.actions}>{allowedEnquiryTransitions(enquiry.status).map((status) => <Pressable disabled={busy} key={status} onPress={() => onTransition(status)} style={[styles.secondary, busy && styles.disabled]}><Text style={styles.secondaryText}>{displayEnquiryStatus(status)}</Text></Pressable>)}</View></View>;
}
function Field({ label, value }: { label: string; value: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }

const styles = StyleSheet.create({ controls: { gap: spacing.md, marginBottom: spacing.lg }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, chip: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.surfaceMuted, borderRadius: radius.chip }, chipSelected: { backgroundColor: colors.primaryDark }, chipText: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 11 }, chipTextSelected: { color: colors.textOnPrimary }, search: { minHeight: touchTarget.min, paddingHorizontal: spacing.md, color: colors.textPrimary, backgroundColor: colors.surface, borderColor: colors.borderStrong, borderRadius: radius.control, borderWidth: 1, fontFamily: fontFamilies.body }, list: { gap: spacing.md }, card: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, grow: { flex: 1 }, name: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 18 }, pg: { color: colors.primaryDark, fontFamily: fontFamilies.bodyMedium, fontSize: 13 }, fields: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, padding: spacing.md, backgroundColor: colors.background, borderRadius: radius.lg }, field: { width: '45%', gap: spacing.xxs }, label: { color: colors.textTertiary, fontFamily: fontFamilies.body, fontSize: 11 }, value: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 13 }, primary: { minHeight: touchTarget.min, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primaryDark, borderRadius: radius.control }, primaryText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, secondary: { minHeight: 40, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.primaryMuted, borderRadius: radius.control }, secondaryText: { color: colors.primaryDark, fontFamily: fontFamilies.bodySemiBold, fontSize: 12 }, disabled: { opacity: 0.5 } });
