import { useMemo, useState } from 'react';
import type { Href } from 'expo-router';
import { useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { MerchantVisit, VisitRescheduleInput } from '@/contracts/merchantVisit';
import { MerchantScreen } from '@/components/native/MerchantScreen';
import { ConfirmationAction, EmptyState, InlineError, LoadingState, MutationLoading, RetryState, StatusBadge, SuccessFeedback } from '@/components/native/ScreenStates';
import { RescheduleVisitModal, VisitActions, visitActionLabel } from '@/components/native/visits/VisitActions';
import { colors, fontFamilies, radius, spacing, touchTarget } from '@/design-system';
import { displayVisitStatus } from '@/features/merchantVisits/mapper';
import { useCompleteVisit, useConfirmVisit, useMarkVisitNoShow, useMerchantVisits, useRejectVisit, useRescheduleVisit } from '@/features/merchantVisits/hooks/useMerchantVisits';
import { filterMerchantVisits, merchantVisitError, merchantVisitFilters, visitStatusTone, type MerchantVisitFilter } from '@/features/merchantVisits/presentation';
import type { MerchantVisitAction } from '@/features/merchantVisits/transitions';
import { merchantRoutes } from '@/navigation/merchantRoutes';

export default function MerchantVisits() {
  const router = useRouter(); const query = useMerchantVisits(); const confirm = useConfirmVisit(); const reject = useRejectVisit(); const complete = useCompleteVisit(); const noShow = useMarkVisitNoShow(); const reschedule = useRescheduleVisit();
  const [filter, setFilter] = useState<MerchantVisitFilter>('ALL'); const [pending, setPending] = useState<{ id: string; action: Exclude<MerchantVisitAction, 'reschedule'> } | null>(null); const [rescheduleId, setRescheduleId] = useState(''); const [notice, setNotice] = useState(''); const [error, setError] = useState('');
  const items = useMemo(() => filterMerchantVisits(query.data ?? [], filter), [query.data, filter]); const busy = confirm.isPending || reject.isPending || complete.isPending || noShow.isPending || reschedule.isPending;
  const done = (message: string) => { setError(''); setNotice(message); setPending(null); }; const fail = (reason: unknown) => { setNotice(''); setError(merchantVisitError(reason)); setPending(null); };
  const requestAction = (id: string, action: MerchantVisitAction) => { setNotice(''); setError(''); if (action === 'reschedule') setRescheduleId(id); else setPending({ id, action }); };
  const perform = () => { if (!pending) return; const options = { onSuccess: () => done(`Visit ${visitActionLabel(pending.action).toLowerCase()} successful.`), onError: fail }; if (pending.action === 'confirm') confirm.mutate({ id: pending.id }, options); else if (pending.action === 'reject') reject.mutate({ id: pending.id }, options); else if (pending.action === 'complete') complete.mutate({ id: pending.id }, options); else noShow.mutate({ id: pending.id }, options); };
  const submitReschedule = (input: VisitRescheduleInput) => reschedule.mutate({ id: rescheduleId, ...input }, { onSuccess: () => { setRescheduleId(''); done('Visit reschedule requested.'); }, onError: fail });
  return <MerchantScreen title="Visits" subtitle="Scheduled tenant visits" refreshing={query.isRefetching} onRefresh={() => void query.refetch()}><View style={styles.filters}>{merchantVisitFilters.map((status) => <Pressable key={status} onPress={() => setFilter(status)} style={[styles.chip, filter === status && styles.chipSelected]}><Text style={[styles.chipText, filter === status && styles.chipTextSelected]}>{status === 'ALL' ? 'All' : displayVisitStatus(status)}</Text></Pressable>)}</View>{notice ? <SuccessFeedback message={notice} /> : null}{error ? <InlineError message={error} /> : null}{busy ? <MutationLoading label="Updating visit..." /> : null}{query.isPending ? <LoadingState label="Loading visits..." /> : query.isError ? <RetryState title="Could not load visits" message={merchantVisitError(query.error)} onRetry={() => void query.refetch()} /> : !items.length ? <EmptyState title="No visits found" message={!query.data?.length ? 'New visit requests will appear here.' : 'No visits match this status.'} /> : <View style={styles.list}>{items.map((visit) => <VisitCard key={visit.id} visit={visit} busy={busy} onView={() => router.push({ pathname: merchantRoutes.visitDetail, params: { id: visit.id } } as Href)} onAction={(action) => requestAction(visit.id, action)} />)}</View>}<ConfirmationAction visible={Boolean(pending)} title={`${pending ? visitActionLabel(pending.action) : 'Update'} visit?`} message="The backend will validate the current visit state before applying this action." confirmLabel={pending ? visitActionLabel(pending.action) : 'Update'} busy={busy} onCancel={() => setPending(null)} onConfirm={perform} /><RescheduleVisitModal visible={Boolean(rescheduleId)} busy={reschedule.isPending} onClose={() => setRescheduleId('')} onSubmit={submitReschedule} /></MerchantScreen>;
}
function VisitCard({ visit, busy, onView, onAction }: { visit: MerchantVisit; busy: boolean; onView: () => void; onAction: (action: MerchantVisitAction) => void }) { return <View style={styles.card}><View style={styles.heading}><View style={styles.grow}><Text style={styles.name}>{visit.user.name}</Text><Text style={styles.pg}>{visit.pg.name}</Text></View><StatusBadge label={displayVisitStatus(visit.status)} tone={visitStatusTone(visit.status)} /></View><View style={styles.fields}><Field label="Visit date" value={visit.requestedDate} /><Field label="Visit time" value={visit.requestedTime} /><Field label="Phone" value={visit.user.phone} /><Field label="Requested" value={new Date(visit.createdAt).toLocaleDateString('en-IN')} /></View><Pressable onPress={onView} style={styles.primary}><Text style={styles.primaryText}>View details</Text></Pressable><VisitActions status={visit.status} busy={busy} onAction={onAction} /></View>; }
function Field({ label, value }: { label: string; value: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ filters: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginBottom: spacing.lg }, chip: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: colors.surfaceMuted, borderRadius: radius.chip }, chipSelected: { backgroundColor: colors.primaryDark }, chipText: { color: colors.textSecondary, fontFamily: fontFamilies.bodyMedium, fontSize: 11 }, chipTextSelected: { color: colors.textOnPrimary }, list: { gap: spacing.md }, card: { gap: spacing.md, padding: spacing.lg, backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1 }, heading: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, grow: { flex: 1 }, name: { color: colors.textPrimary, fontFamily: fontFamilies.heading, fontSize: 18 }, pg: { color: colors.primaryDark, fontFamily: fontFamilies.bodyMedium, fontSize: 13 }, fields: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, padding: spacing.md, backgroundColor: colors.background, borderRadius: radius.lg }, field: { width: '45%', gap: spacing.xxs }, label: { color: colors.textTertiary, fontFamily: fontFamilies.body, fontSize: 11 }, value: { color: colors.textPrimary, fontFamily: fontFamilies.bodySemiBold, fontSize: 13 }, primary: { minHeight: touchTarget.min, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primaryDark, borderRadius: radius.control }, primaryText: { color: colors.textOnPrimary, fontFamily: fontFamilies.bodySemiBold } });
