import { describe, expect, it } from 'vitest';
import type { MerchantSelfProfileDto } from '../../contracts/merchantProfile';
import { merchantProfileToForm, merchantProfileUpdatePayload } from './presentation';
import { merchantProfileFormSchema } from './validation';

const profile: MerchantSelfProfileDto = { id: 'm1', publicId: 'merchant-1', fullName: 'Owner Name', phone: '+91 90000 00000', email: null, profilePhotoUrl: null, business: { name: 'Stay Business', type: 'Individual', gstNumber: null, panNumber: null }, address: { businessAddress: null, city: 'Pune', state: null, pincode: null }, payment: { qrUrl: null, upiId: null }, onboarding: { completed: true }, access: { status: 'ACTIVE', approvedAt: null, rejectedAt: null, suspendedAt: null, statusReason: null }, timestamps: { createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' } };
describe('merchant profile presentation and validation', () => {
  it('maps backend profile fields without fabricating nullable values', () => { const form = merchantProfileToForm(profile); expect(form).toMatchObject({ fullName: 'Owner Name', email: '', businessName: 'Stay Business', city: 'Pune' }); expect(form.profilePhotoUrl).toBe(''); });
  it('builds only backend-editable fields and normalizes nullable and tax values', () => { const payload = merchantProfileUpdatePayload({ ...merchantProfileToForm(profile), gstNumber: '27abcde1234f1z5', panNumber: 'abcde1234f', email: ' ' }); expect(payload).toMatchObject({ gstNumber: '27ABCDE1234F1Z5', panNumber: 'ABCDE1234F', email: null }); expect(payload).not.toHaveProperty('merchantId'); expect(payload).not.toHaveProperty('status'); expect(payload).not.toHaveProperty('phone'); });
  it('accepts valid editable data', () => expect(merchantProfileFormSchema.safeParse({ ...merchantProfileToForm(profile), email: 'owner@example.com', profilePhotoUrl: 'https://example.com/photo.jpg' }).success).toBe(true));
  it('rejects invalid email, non-HTTPS URLs, pincode, tax IDs and unknown fields', () => { const base = merchantProfileToForm(profile); expect(merchantProfileFormSchema.safeParse({ ...base, email: 'bad' }).success).toBe(false); expect(merchantProfileFormSchema.safeParse({ ...base, profilePhotoUrl: 'http://example.com/a.jpg' }).success).toBe(false); expect(merchantProfileFormSchema.safeParse({ ...base, pincode: '123' }).success).toBe(false); expect(merchantProfileFormSchema.safeParse({ ...base, panNumber: 'wrong' }).success).toBe(false); expect(merchantProfileFormSchema.safeParse({ ...base, merchantId: 'forged' }).success).toBe(false); });
});
